CREATE TABLE IF NOT EXISTS STUDENT(
    NAME TEXT,
    AGE NUMBER,
    GRADE NUMBER
);

INSERT INTO STUDENT(NAME,AGE,GRADE)
VALUES
    ("HARRY",12,7),
    ("KEL",16,10),
    ("SNUUY",15,10),
    ("aRUBYSA",16,10),
    ("SUSHI",6,1),
    ("RANDOM_KID",18,12),
    ("ZHONGLEE",6000,5005);

SELECT NAME, AGE,GRADE
    FROM STUDENT
    WHERE AGE = (SELECT MIN(AGE)FROM STUDENT);
SELECT NAME, AGE,GRADE
    FROM STUDENT
    WHERE AGE = (SELECT MAX(AGE)FROM STUDENT);

